// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assignments": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes an assignment JSON and stores in DB. Returns saved JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assignment"
                ],
                "summary": "Create a new Assignment",
                "parameters": [
                    {
                        "description": "Assignment JSON",
                        "name": "assignment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateAssignment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateAssignment"
                        }
                    }
                }
            }
        },
        "/assignments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the assignment whose ID value matches the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assignment"
                ],
                "summary": "Get single assignment by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read assignment by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateAssignment"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single assignment whose ID value matches the id. New data must be passed in the body.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assignment"
                ],
                "summary": "Update single assignment by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update assignment by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Assignment JSON",
                        "name": "assignment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateAssignment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateAssignment"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single assignment from the repository based on id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assignment"
                ],
                "summary": "Remove single assignment by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete assignment by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/courses": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a course JSON and stores in DB. Returns saved JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "Create a new Course",
                "parameters": [
                    {
                        "description": "Course JSON",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateCourse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateCourse"
                        }
                    }
                }
            }
        },
        "/courses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the course whose ID value matches the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "Get single course by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read course by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateCourse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single course whose ID value matches the id. New data must be passed in the body.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "Update single course by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update course by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Course JSON",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateCourse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateCourse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single course from the repository based on id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "Remove single course by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete course by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/documents": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a document JSON and stores in DB. Returns saved JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document"
                ],
                "summary": "Create a new Document",
                "parameters": [
                    {
                        "description": "Document JSON",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateDocument"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateDocument"
                        }
                    }
                }
            }
        },
        "/documents/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the document whose ID value matches the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document"
                ],
                "summary": "Get single document by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read document by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateDocument"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single document whose ID value matches the id. New data must be passed in the body.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document"
                ],
                "summary": "Update single document by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update document by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Document JSON",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateDocument"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateDocument"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single document from the repository based on id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document"
                ],
                "summary": "Remove single document by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete document by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/enrollments": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes an enrollment JSON and stores in DB. Returns saved JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollment"
                ],
                "summary": "Create a new Enrollment",
                "parameters": [
                    {
                        "description": "Enrollment JSON",
                        "name": "enrollment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateEnrollment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateEnrollment"
                        }
                    }
                }
            }
        },
        "/enrollments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the enrollment whose ID value matches the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollment"
                ],
                "summary": "Get single enrollment by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read enrollment by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateEnrollment"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single enrollment whose ID value matches the id. New data must be passed in the body.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollment"
                ],
                "summary": "Update single enrollment by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update enrollment by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Enrollment JSON",
                        "name": "enrollment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateEnrollment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateEnrollment"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single enrollment from the repository based on id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollment"
                ],
                "summary": "Remove single enrollment by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete enrollment by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/file": {
            "get": {
                "description": "Lấy tệp từ bucket 'media' của MinIO hoặc trả về URL đã ký trước để truy cập tệp. Yêu cầu tên object của tệp.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minio"
                ],
                "summary": "Lấy tệp từ MinIO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tên object của tệp (bao gồm thư mục, ví dụ: images/example.jpg)",
                        "name": "objectName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Truy xuất tệp thành công",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Yêu cầu không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Tệp không tồn tại",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/grades": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a grade JSON and stores in DB. Returns saved JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grade"
                ],
                "summary": "Create a new Grade",
                "parameters": [
                    {
                        "description": "Grade JSON",
                        "name": "grade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateGrade"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateGrade"
                        }
                    }
                }
            }
        },
        "/grades/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the grade whose ID value matches the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grade"
                ],
                "summary": "Get single grade by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read grade by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateGrade"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single grade whose ID value matches the id. New data must be passed in the body.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grade"
                ],
                "summary": "Update single grade by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update grade by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Grade JSON",
                        "name": "grade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateGrade"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateGrade"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single grade from the repository based on id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grade"
                ],
                "summary": "Remove single grade by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete grade by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Use this for liveness probes or any other checks which only validate if the services is running.",
                "tags": [
                    "healthcheck"
                ],
                "summary": "Health is used to handle HTTP Health requests to this service.",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/notifications": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a notification JSON and stores in DB. Returns saved JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Create a new Notification",
                "parameters": [
                    {
                        "description": "Notification JSON",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateNotification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateNotification"
                        }
                    }
                }
            }
        },
        "/notifications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the notification whose ID value matches the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Get single notification by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read notification by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateNotification"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single notification whose ID value matches the id. New data must be passed in the body.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Update single notification by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update notification by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Notification JSON",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateNotification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateNotification"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single notification from the repository based on id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Remove single notification by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete notification by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/submissions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a submission JSON and stores in DB. Returns saved JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Submission"
                ],
                "summary": "Create a new Submission",
                "parameters": [
                    {
                        "description": "Submission JSON",
                        "name": "submission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateSubmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateSubmission"
                        }
                    }
                }
            }
        },
        "/submissions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the submission whose ID value matches the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Submission"
                ],
                "summary": "Get single submission by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read submission by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateSubmission"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single submission whose ID value matches the id. New data must be passed in the body.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Submission"
                ],
                "summary": "Update single submission by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update submission by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Submission JSON",
                        "name": "submission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateSubmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateSubmission"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single submission from the repository based on id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Submission"
                ],
                "summary": "Remove single submission by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete submission by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Tải file lên bucket 'media' của MinIO. Định dạng hỗ trợ: JPG, PNG, MP4, PDF, DOC, DOCX, XLS, XLSX.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minio"
                ],
                "summary": "Tải file lên MinIO",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File cần tải lên",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tải file thành công",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "File hoặc yêu cầu không hợp lệ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Lỗi server",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all users from the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-array_github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-array_github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a user JSON and stores in DB. Returns saved JSON.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create a new User",
                "parameters": [
                    {
                        "description": "User JSON",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateUser"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateUser"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the user whose ID value matches the id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get single user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Read user by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates and returns a single user whose ID value matches the id. New data must be passed in the body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update single user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update user by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User JSON",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a single user from the repository based on id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Remove single user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete user by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_User"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateAssignment": {
            "type": "object",
            "required": [
                "CourseID",
                "CreatedBy",
                "DueDate",
                "Title"
            ],
            "properties": {
                "CourseID": {
                    "type": "integer"
                },
                "CreatedBy": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "DueDate": {
                    "type": "string"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateCourse": {
            "type": "object",
            "required": [
                "TeacherID",
                "Title"
            ],
            "properties": {
                "Description": {
                    "type": "string"
                },
                "TeacherID": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateDocument": {
            "type": "object",
            "required": [
                "CourseID",
                "FileType",
                "FileURL",
                "Title",
                "UploadedBy"
            ],
            "properties": {
                "CourseID": {
                    "type": "integer"
                },
                "FileType": {
                    "type": "string",
                    "enum": [
                        "pdf",
                        "video",
                        "image"
                    ]
                },
                "FileURL": {
                    "type": "string"
                },
                "Title": {
                    "type": "string"
                },
                "UploadedBy": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateEnrollment": {
            "type": "object",
            "required": [
                "CourseID",
                "UserID"
            ],
            "properties": {
                "CourseID": {
                    "type": "integer"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateGrade": {
            "type": "object",
            "required": [
                "GradedBy",
                "Score",
                "SubmissionID"
            ],
            "properties": {
                "Feedback": {
                    "type": "string"
                },
                "GradedBy": {
                    "type": "integer"
                },
                "Score": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "SubmissionID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateNotification": {
            "type": "object",
            "required": [
                "Content",
                "Type",
                "UserID"
            ],
            "properties": {
                "Content": {
                    "type": "string"
                },
                "IsRead": {
                    "type": "boolean"
                },
                "Type": {
                    "type": "string",
                    "enum": [
                        "assignment",
                        "grade",
                        "course",
                        "system"
                    ]
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateSubmission": {
            "type": "object",
            "required": [
                "AssignmentID",
                "UserID"
            ],
            "properties": {
                "AssignmentID": {
                    "type": "integer"
                },
                "FileURL": {
                    "type": "string"
                },
                "TextContent": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.CreateUser": {
            "type": "object",
            "required": [
                "Email",
                "FullName",
                "Password",
                "Role",
                "Username"
            ],
            "properties": {
                "AvatarURL": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FullName": {
                    "type": "string"
                },
                "Password": {
                    "type": "string"
                },
                "Role": {
                    "type": "string",
                    "enum": [
                        "student",
                        "teacher",
                        "admin"
                    ]
                },
                "TelegramID": {
                    "type": "string"
                },
                "UserID": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-array_github_com_hoangtu1372k2_vms_internal_model_UpdateUser": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateUser"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateAssignment": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateAssignment"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateCourse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateCourse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateDocument": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateDocument"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateEnrollment": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateEnrollment"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateGrade": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateGrade"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateNotification": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateNotification"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateSubmission": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateSubmission"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_CreateUser": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.CreateUser"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateAssignment": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateAssignment"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateCourse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateCourse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateDocument": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateDocument"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateEnrollment": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateEnrollment"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateGrade": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateGrade"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateNotification": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateNotification"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateSubmission": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateSubmission"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_UpdateUser": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.UpdateUser"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.JsonDTORsp-github_com_hoangtu1372k2_vms_internal_model_User": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_hoangtu1372k2_vms_internal_model.User"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateAssignment": {
            "type": "object",
            "properties": {
                "AssignmentID": {
                    "type": "integer"
                },
                "CourseID": {
                    "type": "integer"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "CreatedBy": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "DueDate": {
                    "type": "string"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateCourse": {
            "type": "object",
            "properties": {
                "CourseID": {
                    "type": "integer"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "TeacherID": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateDocument": {
            "type": "object",
            "properties": {
                "CourseID": {
                    "type": "integer"
                },
                "DocumentID": {
                    "type": "integer"
                },
                "FileType": {
                    "type": "string"
                },
                "FileURL": {
                    "type": "string"
                },
                "Title": {
                    "type": "string"
                },
                "UploadedAt": {
                    "type": "string"
                },
                "UploadedBy": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateEnrollment": {
            "type": "object",
            "properties": {
                "CourseID": {
                    "type": "integer"
                },
                "EnrolledAt": {
                    "type": "string"
                },
                "EnrollmentID": {
                    "type": "integer"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateGrade": {
            "type": "object",
            "properties": {
                "Feedback": {
                    "type": "string"
                },
                "GradeID": {
                    "type": "integer"
                },
                "GradedAt": {
                    "type": "string"
                },
                "GradedBy": {
                    "type": "integer"
                },
                "Score": {
                    "type": "number"
                },
                "SubmissionID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateNotification": {
            "type": "object",
            "properties": {
                "Content": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "IsRead": {
                    "type": "boolean"
                },
                "NotificationID": {
                    "type": "integer"
                },
                "Type": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateSubmission": {
            "type": "object",
            "properties": {
                "AssignmentID": {
                    "type": "integer"
                },
                "FileURL": {
                    "type": "string"
                },
                "SubmissionID": {
                    "type": "integer"
                },
                "SubmittedAt": {
                    "type": "string"
                },
                "TextContent": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.UpdateUser": {
            "type": "object",
            "properties": {
                "AvatarURL": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FullName": {
                    "type": "string"
                },
                "Role": {
                    "type": "string"
                },
                "TelegramID": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                },
                "UserID": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "github_com_hoangtu1372k2_vms_internal_model.User": {
            "type": "object",
            "properties": {
                "AvatarURL": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "FullName": {
                    "type": "string"
                },
                "Password": {
                    "type": "string"
                },
                "Role": {
                    "type": "string"
                },
                "TelegramID": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                },
                "UserID": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "internal_auth.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "fullname",
                "password",
                "role",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "student",
                        "teacher",
                        "admin"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_auth.TokenResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your bearer token in the format: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
